FROM python:3.11-slim

WORKDIR /app

# System deps for psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install backend deps
COPY requirements/api.txt ./requirements/api.txt
RUN pip install --no-cache-dir -r requirements/api.txt

# Copy application + model artifacts
COPY api ./api
COPY src ./src
COPY mlruns ./mlruns
COPY mlflow.db .

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
